=== AndrewBurian/WebSoft/data/xml/locations.dtd
<!--
    DTD to validate bar and pub listings.
-->

<!-- "ESTABLISHMENTS" is the root element. It holds bars which consist of bar names, branch if applicable, address and capacity -->
<!ELEMENT ESTABLISHMENTS (CITY)+>
<!-- "ESTABLISHMENTS" has a single attribute, an HREF for the source of the data -->
<!ATTLIST ESTABLISHMENTS
    source CDATA    #REQUIRED
>
<!-- "city" has a single attribute, the name of the city the establishment is in.  To be used for sorting -->
<!ELEMENT CITY (BAR)+>
<!ATTLIST CITY	name 	CDATA 	#REQUIRED>

<!-- Bars are defined in nested elements; bar names, branch if applicable, address and capacity-->
<!ELEMENT BAR (NAME, BRANCH?, ADDRESS, CAPACITY)>

<!ELEMENT NAME (#PCDATA)>
<!ELEMENT BRANCH (#PCDATA)>
<!ELEMENT ADDRESS (#PCDATA)>
<!ELEMENT CAPACITY (#PCDATA)>

=== AndrewBurian/WebSoft/data/xml/locations.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='locations.xsl'?>
<!--
locations.xml

This XML document is a listing of bars, pubs and lounges in the Lower Mainland
Original data came from the BC Ministry of Justice, Liquor Control and Licensing Branch, List of Licensed Establishments in BC
Data is a selected subset of establishments with a 'Liquor Only' license
HREF: www.pssg.gov.bc.ca/lclb/licensed/all-location.htm
-->

<!--<!DOCTYPE ESTABLISHMENTS SYSTEM 'locations.dtd'>-->



<ESTABLISHMENTS source = "www.pssg.gov.bc.ca/lclb/licensed/all-location.htm"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="locations.xsd">
    <CITY name = "Aldergrove">
        <BAR>
            <NAME>Alder Inn Hotel</NAME>
            <ADDRESS>27214 Fraser Hwy</ADDRESS>
            <CAPACITY>125</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Fox &amp; Hounds Neighbourhood Pub</NAME>
            <ADDRESS>26444  32nd Ave</ADDRESS>
            <CAPACITY>150</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Mustangs Bar</NAME>
            <ADDRESS>7-3227 264 Street</ADDRESS>
            <CAPACITY>312</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Royal Canadian Legion</NAME>
            <BRANCH>Branch No. 265</BRANCH>
            <ADDRESS>26607 Fraser Hwy</ADDRESS>
            <CAPACITY>510</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Royal Westminster Regiment - Aldergrove Mess</NAME>
            <ADDRESS>Building 2, CFS Aldergrove, 272 Street</ADDRESS>
            <CAPACITY>100</CAPACITY>
        </BAR>
    </CITY>
    <CITY name = "Burnaby">
        <BAR>
            <NAME>Admiral Pub &amp; Grill</NAME>
            <ADDRESS>4125 E Hastings St</ADDRESS>
            <CAPACITY>250</CAPACITY>
        </BAR>
        <BAR>
            <NAME>BEST WESTERN KINGS INN</NAME>
            <ADDRESS>5411 KINGSWAY</ADDRESS>
            <CAPACITY>67</CAPACITY>
        </BAR>
        <BAR>
            <NAME>BRENTWOOD LANES</NAME>
            <ADDRESS>5502 LOUGHEED HWY</ADDRESS>
            <CAPACITY>45</CAPACITY>
        </BAR>
        <BAR>
            <NAME>BRENTWOOD RACQUETBALL CLUB</NAME>
            <ADDRESS>5502 LOUGHEED HWY</ADDRESS>
            <CAPACITY>100</CAPACITY>
        </BAR>
        <BAR>
            <NAME>BURNABY WINTER CLUB</NAME>
            <ADDRESS>4990 CANADA WAY</ADDRESS>
            <CAPACITY>190</CAPACITY>
        </BAR>
        <BAR>
            <NAME>EAGLE CREEK AT BURNABY MOUNTAIN</NAME>
            <ADDRESS>7600 HALIFAX ST</ADDRESS>
            <CAPACITY>175</CAPACITY>
        </BAR>
        <BAR>
            <NAME>EXECUTIVE INN HOTEL</NAME>
            <ADDRESS>4201 LOUGHEED HWY</ADDRESS>
            <CAPACITY>35</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Firefighters Hose N Hydrant Public House</NAME>
            <ADDRESS>6515 Bonsor Avenue</ADDRESS>
            <CAPACITY>200</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Grand Villa Casino &amp; Hotel</NAME>
            <ADDRESS>4331 Dominion St</ADDRESS>
            <CAPACITY>20</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Grand Villa Casino &amp; Hotel</NAME>
            <ADDRESS>4331 Dominion Street</ADDRESS>
            <CAPACITY>4344</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Great Bear Pub &amp; Liquor Store </NAME>
            <ADDRESS>5665 KINGSWAY</ADDRESS>
            <CAPACITY>208</CAPACITY>
        </BAR>
        <BAR>
            <NAME>HILTON VANCOUVER METROTOWN</NAME>
            <ADDRESS>6083 MCKAY AVENUE</ADDRESS>
            <CAPACITY>149</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Holiday Inn</NAME>
            <BRANCH>Metrotown</BRANCH>
            <ADDRESS>4405 Central Blvd</ADDRESS>
            <CAPACITY>225</CAPACITY>
        </BAR>
        <BAR>
            <NAME>HOP &amp; VINE NEIGHBOURHOOD PUB &amp; BEER STORE</NAME>
            <ADDRESS>9 1601 BURNWOOD DR</ADDRESS>
            <CAPACITY>85</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Joey Burnaby Grill Lounge</NAME>
            <ADDRESS>107-1899 Rosser Ave</ADDRESS>
            <CAPACITY>124</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Lougheed Village Bar and Grill</NAME>
            <ADDRESS>9532 ERICKSON DR</ADDRESS>
            <CAPACITY>356</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Marine Neighbourhood Pub</NAME>
            <ADDRESS>5820 Marine Dr</ADDRESS>
            <CAPACITY>175</CAPACITY>
        </BAR>
        <BAR>
            <NAME>MOUNTAIN SHADOW INN</NAME>
            <ADDRESS>7174 BARNET RD</ADDRESS>
            <CAPACITY>160</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Oliver Twist Pub</NAME>
            <ADDRESS>7557 Edmonds St</ADDRESS>
            <CAPACITY>80</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Professor Mugs Pub and Grill</NAME>
            <ADDRESS>3700 WILLINGDON AVE</ADDRESS>
            <CAPACITY>346</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Riverway Golf Course</NAME>
            <ADDRESS>9001 Bill Fox Way</ADDRESS>
            <CAPACITY>154</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Royal Canadian Legion</NAME>
            <BRANCH>Branch No. 83</BRANCH>
            <ADDRESS>5289 Grimmer Street</ADDRESS>
            <CAPACITY>100</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Royal Canadian Legion</NAME>
            <BRANCH>Branch No. 148</BRANCH>
            <ADDRESS>4356 E  HASTINGS ST</ADDRESS>
            <CAPACITY>425</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Wings Tap &amp; Grill Kingsway</NAME>
            <ADDRESS>6879 Kingsway</ADDRESS>
            <CAPACITY>115</CAPACITY>
        </BAR>
    </CITY>
    <CITY name = "Coquitlam">
        <BAR>
            <NAME>Charlie Hamilton's Pub</NAME>
            <ADDRESS>1031-1037  1163 Pinetree Way</ADDRESS>
            <CAPACITY>60</CAPACITY>
        </BAR>
        <BAR>
            <NAME>COQUITLAM INN AND CONVENTION CENTRE</NAME>
            <ADDRESS>319 NORTH RD</ADDRESS>
            <CAPACITY>106</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Executive Plaza Coquitlam</NAME>
            <ADDRESS>405 North Rd</ADDRESS>
            <CAPACITY>72</CAPACITY>
        </BAR>
        <BAR>
            <NAME>FROG AND NIGHTGOWN</NAME>
            <ADDRESS>1125 FALCON DR</ADDRESS>
            <CAPACITY>170</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Hard Rock Casino Vancouver</NAME>
            <ADDRESS>2080 United Blvd.</ADDRESS>
            <CAPACITY>2953</CAPACITY>
        </BAR>
        <BAR>
            <NAME>John B Pub</NAME>
            <ADDRESS>1000 Austin Ave</ADDRESS>
            <CAPACITY>282</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Micky's Public House</NAME>
            <ADDRESS>170 Golden Drive</ADDRESS>
            <CAPACITY>215</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Milestone's Restaurant &amp; Palomino Bar</NAME>
            <ADDRESS>2745 Barnet Hwy</ADDRESS>
            <CAPACITY>118</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Planet Ice</NAME>
            <BRANCH>Boomers - Coquitlam</BRANCH>
            <ADDRESS>2300 ROCKET WAY</ADDRESS>
            <CAPACITY>225</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Ramada Hotel</NAME>
            <ADDRESS>631 Lougheed Hwy </ADDRESS>
            <CAPACITY>60</CAPACITY>
        </BAR>
        <BAR>
            <NAME>RHINO'S</NAME>
            <ADDRESS>541 CLARKE RD</ADDRESS>
            <CAPACITY>208</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Roos Pub &amp; Grill</NAME>
            <ADDRESS>2962 Christmas Way</ADDRESS>
            <CAPACITY>179</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Royal Canadian Legion</NAME>
            <BRANCH>Branch No. 263</BRANCH>
            <ADDRESS>1025 Ridgeway Ave</ADDRESS>
            <CAPACITY>422</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Town Hall Public House</NAME>
            <BRANCH>Coquitlam</BRANCH>
            <ADDRESS>925 Brunette Avenue</ADDRESS>
            <CAPACITY>145</CAPACITY>
        </BAR>
        <BAR>
            <NAME>VANCOUVER GOLF CLUB</NAME>
            <ADDRESS>771 AUSTIN AVE</ADDRESS>
            <CAPACITY>542</CAPACITY>
        </BAR>
        <BAR>
            <NAME>VIP Lounge and Cinemas</NAME>
            <ADDRESS>170 Schoolhouse Street</ADDRESS>
            <CAPACITY>591</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Westwood Plateau Golf - Executive 12 Hole Course</NAME>
            <ADDRESS>1630 PARKWAY BLVD</ADDRESS>
            <CAPACITY>32</CAPACITY>
        </BAR>
        <BAR>
            <NAME>WESTWOOD PLATEAU GOLF &amp; COUNTRY CLUB</NAME>
            <ADDRESS>3251 WESTWOOD PLATEAU BLVD</ADDRESS>
            <CAPACITY>23</CAPACITY>
        </BAR>
        <BAR>
            <NAME>WOODY'S ON BRUNETTE</NAME>
            <ADDRESS>935 BRUNETTE ST</ADDRESS>
            <CAPACITY>255</CAPACITY>
        </BAR>
    </CITY>
    <CITY name = "Delta">
        <BAR>
            <NAME>BEACH GROVE GOLF CLUB</NAME>
            <ADDRESS>5946 - 12TH AVE</ADDRESS>
            <CAPACITY>196</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Browns Social House (Tsawwassen)</NAME>
            <ADDRESS>1665 56th St</ADDRESS>
            <CAPACITY>23</CAPACITY>
        </BAR>
        <BAR>
            <NAME>CAPTAIN'S COVE MARINA</NAME>
            <ADDRESS>6100 FERRY RD</ADDRESS>
            <CAPACITY>71</CAPACITY>
        </BAR>
        <BAR>
            <NAME>Delta Golf Club</NAME>
            <ADDRESS>11550 Ladner Trunk Rd</ADDRESS>
            <CAPACITY>152</CAPACITY>
        </BAR>
        <BAR>
            <NAME>DELTA LION PUB &amp; BISTRO</NAME>
            <ADDRESS>11186 84TH AVE</ADDRESS>
            <CAPACITY>208</CAPACITY>
        </BAR>
        <BAR>
            <NAME>DELTA TOWN &amp; COUNTRY INN</NAME>
